name: VRP
main: com.jordair.gmail.VoteReceiver.VoteReceiverPlugin
version: 1.0
depend: [SQLibrary, Votifier]
author: MrTeePee

commands:
  vr:
    description: Display the top 10 voters.
    permission: votes.view
    permission-message: You don't have permission.
  vc:
    description: Display the number of votes made since voting opened.
    permission: votes.view
    permission-message: You don't have permission.
  vs:
    description: Spoof a vote.
    permission: votes.spoof
    permission-message: You don't have permission.
  vrc:
    description: Clear the voting log.
    aliases: vclear
    permission: votes.clear
    permission-message: You don't have permission.
  vro:
    description: Open voting.
    aliases: vopen
    permission: votes.open
    permission-message: You don't have permission.
  vrx:
    description: Close voting.
    aliases: vclose
    permission: votes.close
    permission-message: You don't have permission.
  vr (#):
    description: Display the top x voters.
    permission: votes.view
    permission-message: You don't have permission.

permissions:
  votes.user:
    description: Ability to view data and see live updates.
    children:
      votes.view: true
      votes.alert: true
  votes.admin:
    description: Ability to use all commands.
    children:
    votes.user: true
    votes.clear: true
    votes.open: true
    votes.close: true
  votes.view:
    description: Ability to view current vote data.
    default: true
  votes.alert:
    description: Ability to see voting updates in chat.
    default: true
  votes.clear:
    description: Ability to clear database.
    default: op
  votes.open:
    description: Ability to open voting.
    default: op
  votes.close:
    description: Ability to close voting.
    default: op
  votes.spoof:
    description: Ability to submit a fake vote.
    default: op